/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.DAO_HoaDon;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
public class QuanLiHoaDon_pn extends javax.swing.JPanel {

    private DAO.DAO_HoaDon rp = new DAO_HoaDon();
    private DefaultTableModel model = new DefaultTableModel();
    private int i = 2;
    int id;
    public QuanLiHoaDon_pn() {
        initComponents();
        fill_hoaDon(rp.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        HoaDon = new javax.swing.JTable();
        txt_idHd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_tong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jpnRoot.setBackground(new java.awt.Color(204, 204, 255));
        jpnRoot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Hoá Đơn", "Tên Sản Phẩm", "Size", "Color", "Số Lượng", "Đơn Giá", "ID Voucher", "Thành Tiền", "ID Nhân Viên Thanh Toán", "Ngày Tạo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HoaDon);
        if (HoaDon.getColumnModel().getColumnCount() > 0) {
            HoaDon.getColumnModel().getColumn(0).setMinWidth(80);
            HoaDon.getColumnModel().getColumn(0).setMaxWidth(80);
            HoaDon.getColumnModel().getColumn(2).setMinWidth(50);
            HoaDon.getColumnModel().getColumn(2).setMaxWidth(50);
            HoaDon.getColumnModel().getColumn(3).setMinWidth(180);
            HoaDon.getColumnModel().getColumn(3).setMaxWidth(180);
            HoaDon.getColumnModel().getColumn(4).setMinWidth(80);
            HoaDon.getColumnModel().getColumn(4).setMaxWidth(80);
            HoaDon.getColumnModel().getColumn(6).setMinWidth(80);
            HoaDon.getColumnModel().getColumn(6).setMaxWidth(80);
            HoaDon.getColumnModel().getColumn(8).setMinWidth(140);
            HoaDon.getColumnModel().getColumn(8).setMaxWidth(140);
        }

        jpnRoot.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 168, 1686, 496));

        txt_idHd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_idHd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idHdActionPerformed(evt);
            }
        });
        jpnRoot.add(txt_idHd, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 32, 288, 37));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Tìm Kiếm Hoá Đơn");
        jpnRoot.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 40, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Tìm Kiếm");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpnRoot.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1453, 47, 138, -1));

        txt_tong.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txt_tong.setForeground(new java.awt.Color(255, 0, 0));
        txt_tong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_tong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tongActionPerformed(evt);
            }
        });
        jpnRoot.add(txt_tong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 792, 288, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Tổng Tiền Hoá Đơn");
        jpnRoot.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 797, -1, 50));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Refersh");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jpnRoot.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1453, 98, 138, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MegaTron.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jpnRoot.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 1010));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idHdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idHdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idHdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        String tim = txt_idHd.getText().trim();
        if (rp.timHd(tim).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không Tìm THấy");
        } else {
            // đẩy dl tìm được ra bảng
            this.fill_HD(rp.timHd(tim));
            JOptionPane.showMessageDialog(this, "Danh Sách Tìm Thấy Trong Bảng");
            
            String a = String.valueOf(rp.TongTien(tim));
        long num = Long.parseLong(a);
        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
        symbols.setGroupingSeparator('.');

        DecimalFormat formatter = new DecimalFormat("#,###", symbols);
        String b = formatter.format(num);
            txt_tong.setText(b+" VNĐ");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_tongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tongActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.fill_hoaDon(rp.getAll());
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HoaDon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JPanel jpnRoot = new javax.swing.JPanel();
    private javax.swing.JTextField txt_idHd;
    private javax.swing.JTextField txt_tong;
    // End of variables declaration//GEN-END:variables

    private void fill_hoaDon(ArrayList<model.HoaDon> all) {
       model = (DefaultTableModel) HoaDon.getModel();
       model.setRowCount(0);
        for (model.HoaDon a : all) {
            model.addRow(a.toRowTable());
            
        }
        
    }

    private void fill_HD(ArrayList<HoaDon> tim) {
       model = (DefaultTableModel) HoaDon.getModel();
       model.setRowCount(0);
        for (HoaDon hoaDon : tim) {
         model.addRow(hoaDon.toRowTable());
        }
    }
}
